### ISSUE TITLE
Saved projects don't update the name in .luna-project

### ISSUE THREAD

**Issue by piotrMocz** [luna/luna-studio#1025]
Steps to reproduce:
1. Open a new, empty project.
2. Save it, choosing an arbitrary name other than `UnsavedLunaProject`.
3. Go to the location where you saved the project and inspect the contents of the `.luna-package` directory. You will notice two things:
    3.1. The name of the `*.lunaproject` file is still `UnsavedLunaProject`.
    3.2. The name of the project inside `config.yaml` is `UnsavedLunaProject` as well.

**Comment by iamrecursion** [comment]
This should be implemented by luna/luna#258.

**Comment by iamrecursion** [comment]
Functionality now implemented in https://github.com/luna/luna/pull/260, waiting for review.

**Comment by mikusp** [comment]
@iamrecursion I used this `rename` function instead of my previous implementation, and see that it cannot be done using `Dir.renameDirectory` and `Dir.renameFile`. I get an exception `rename: unsupported operation (Invalid cross-device link)`. You should copy the files and then delete original directory.

**Comment by iamrecursion** [comment]
Will fix when back!

**Comment by iamrecursion** [comment]
Fixed [here](https://github.com/luna/luna/commit/588c2519b3bdcc75e43586256a707a3e3ddf8d19). Needs to be integrated with Studio now.
