### ISSUE TITLE
Binary.take gives Compile error

### ISSUE THREAD

**Issue by akavel** [luna/luna-studio#1029]
A following snippet:

```
test = "x".toBinary . take 1
```

results in an error:

> **Compile error:**
>
> Cannot use object of class Std.Base.Binary as a function.
>
> arising from:
>
> - Std.Base.Binary.take

**Comment by kustosz** [comment]
@akavel thanks for the report! I can confirm the issue. The problem seems to be the definition of `primBinaryTake` and `primBinaryDrop` functions. They are defined as `Binary -> Binary` instead of `Binary -> Int -> Binary` here: https://github.com/luna/luna-core/blob/master/stdlib/src/Luna/Prim/Base.hs#L226. If you're up for opening a pull request to fix that, we'll be happy to accept. Otherwise we'll fix it in house and ship with the next version.

**Comment by akavel** [comment]
I'd be happy to, but I don't have a Haskell compiler and environment for building & testing it. Unless you have a [Nix expression](https://nixos.org/nix) for this that you could quickly share with me? Or you have a github compile/CI bot for PRs? Or I should not worry about compiling this?

**Comment by akavel** [comment]
I tried to compile luna-studio, wishing to be able to test a fix before sending it to you, but didn't manage to complete `./build_luna`, reported my problem as #1042.
