### ISSUE TITLE
Two equivalent notations are not equivalent

### ISSUE THREAD

**Issue by ljkania** [luna/luna-studio#1088]
### General Summary

- Sometimes when you split one node expression into two nodes it is resulting with error.

### Steps to Reproduce

1. Open cryptocurrencies example
2. Find node `response`
3. Delete suffix `. json`
4. Select node and press tab
5. Enter `json` and press enter

### Expected Result

- New node has the same value as previous `response`

### Actual Result

- New node displays error: `Runtime error: Error in $: not enough input`

### Luna Version

- 1.41016

**Comment by piotrMocz** [comment]
This works, it's cool.

Note: distinction between self port and other ports is super confusing. If I didn't know beforehand how to reconnect the node, it would take me a long while to figure it out. Here's a scenario:

1. I follow all the steps from the task description and have a new node named `json1`. I would like to connect it to the `getReal` method, so next, I do this:
2. remove the connection between the `response` and `getReal` nodes
3. click'n'drag from the `json1` node to the `getReal` node and now:
    3.1. the natural step for me is to connect it to the node's border, like any other connection
    3.2. [bad way] I end up disconnecting the thing that was connected there and I end up with this code: `price = getReal json1`, which (quite correctly) results in a compile error.
    3.3. [good way] instead, I need to connect it to the self-port (which is the little dot inside the node) and then everything works fine.

The problem here is that it's very easy to follow the bad way, because it's way more intuitive. @mikusp @wdanilo you guys decide whether this deserves to be a task. If yes, you've got the repro ready ;)
