### ISSUE TITLE
No visualisation with simple arithmetic operation

### ISSUE THREAD

**Issue by wdanilo** [luna/luna-studio#1099]
### General Summary

Using the following code:

```haskell

import Std.Base

def main:
    foo = 7
    foo + 12
```

We get: 

![9](https://user-images.githubusercontent.com/1623053/45883688-13ded880-bdb2-11e8-9af4-8feda5e3d048.png)

There is no result under the second node. If we expand the visualization of the "three loading dots" are seen forever.

Depending on how often it happens it's critical or not, but if it happens in such a simple case, it introduces big confusion.

### Expected Result

- Every node should have a valid visualization. 

### Luna Version
1.4

**Comment by mikusp** [comment]
Computing values for anonymous nodes is implemented in newer version.

21 wrz 2018 15:27 "Wojciech Daniło" <notifications@github.com> napisał(a):

General Summary

Using the following code:

import Std.Base

def main:
    foo = 7
    foo + 12

We get:

[image: 9]
<https://user-images.githubusercontent.com/1623053/45883688-13ded880-bdb2-11e8-9af4-8feda5e3d048.png>

There is no result under the second node. If we expand the visualization of
the "three loading dots" are seen forever.

Depending on how often it happens it's critical or not, but if it happens
in such a simple case, it introduces big confusion.
Expected Result

   - Every node should have a valid visualization.

Luna Version

1.4

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/luna/luna-studio/issues/1099>, or mute the thread

**Comment by mikusp** [comment]
1.5 is released, closing
