### ISSUE TITLE
Tuple visualization is weird when pattern matching, and has a random behavior

### ISSUE THREAD

**Issue by TheOnlyArtz** [luna/luna-studio#1110]
### General Summary

Node which visual a Tuple will have a random behavior, sometime the node will be there, sometime it won't, sometime it will show it's strings, sometimes it won't

### Steps to Reproduce

```elm
def returnTuple:
  ("a", "b")

def main:
  (a, b) = returnTuple # observe the visualization of this
```

### Expected Result

The node will behave just like other nodes

### Actual Result
![image](https://user-images.githubusercontent.com/30025874/45930100-0f5a2180-bf64-11e8-9e3d-15114e6791a4.png)

### Luna Version

- Luna Studio 1.4.101.4

**Comment by wdanilo** [comment]
The code you've pasted is invalid, there is missing colon:

```haskell
def returnTuple <HERE>
  ("a", "b")
```

However this error should be reported on node!

**Comment by wdanilo** [comment]
Confirmed. Another strange thing happens when pattern matching on datatypes, see below. Moreover, we should test creating pattern matches in visual representation, I had a hard problem with it right now and it should be part of this fix.

![9](https://user-images.githubusercontent.com/1623053/45953780-6e26a600-c00b-11e8-8b01-ee22854806cc.png)

**Comment by ljkania** [comment]
With this: https://github.com/luna/luna-studio/pull/1165 it should be fine.
![screen shot 2018-10-03 at 17 52 06](https://user-images.githubusercontent.com/7061422/46423095-0de3e280-c736-11e8-8f06-09e02790d37f.png)
