### ISSUE TITLE
Remove Shelly Dependency from Luna Studio Runner

### ISSUE THREAD

**Issue by iamrecursion** [luna/luna-studio#1374]
### Summary
Currently, a very old `shelly` dependency is keeping [`luna-studio-runner`](https://github.com/luna/luna-studio/blob/master/runner) on a very old LTS (`lts-9.2`). As part of the efforts to modernise this code-base to a newer LTS, it needs to be re-written to use the standard `process` API, rather than `shelly`. 

### Value
Doing this has twofold benefits:

- The package can depend on newer versions of our internal libraries, used directly from the Luna tree.
- The package is closer to allowing Luna Studio to be packaged using `nix` as discussed in https://github.com/luna/luna-manager/issues/127. 

### Specification

- Remove the dependency on the `shelly` library.
- Re-write `luna-studio-runner` to make use of the standard `process` API.

### Acceptance Criteria & Test Cases

- `luna-studio-runner` builds without a dependency on `shelly`. 
- It still performs all of its duties correctly in a Luna Studio package.

**Comment by mulderr** [comment]
Actually `shelly` is on stackage now. It wasn't in lts-8.2, so it is currently listed as an extra-dep in `luna-studio-runner`. That would probably not be needed in lts-12.26 which already has shelly-1.8.1.

We could definitely use `process` or better yet `typed-process` as suggested in the `process` readme but just for the record I don't think `shelly` is the culprit here. Would you still like a PR using `typed-process` instead of `shelly`?

**Comment by iamrecursion** [comment]
That is true, but we've had myriad problems with `shelly` on windows. Furthermore, I think we have had some issues with `typed-process` as well, but I don't know if they have been resolved. @mwu-tow may be able to confirm.

**Comment by mulderr** [comment]
Thanks. Proceeding with `process` then.

**Comment by iamrecursion** [comment]
You may want to wait for Michal to explain in case the issue has been resolved! I would certainly _prefer_ that `typed-process` gets used if the problem I seem to remember no longer exists.

**Comment by mwu-tow** [comment]
IIRC shelly does not prevent us from using the newer lts in the runner, as we can always use extra-deps. It was the case with Bootstrap.hs which was stack-based script that couldn't declare required shelly version.

Still, we do very much want to stop using shelly because it is broken in so many ways, particularly on Windows. Like changing the casing of names of environment variables for process spawned. Or not compiling for the last year.

> Actually shelly is on stackage now. It wasn't in lts-8.2, so it is currently listed as an extra-dep in luna-studio-runner. That would probably not be needed in lts-12.26 which already has shelly-1.8.1.

That's the problem. `shelly-1.8.1`  doesn't support windows — see: https://github.com/yesodweb/Shelly.hs/issues/176
Still, we should be able to pin older version as extra-dep. 

> Furthermore, I think we have had some issues with typed-process as well, but I don't know if they have been resolved.

I remember this but that was part of more complex code. I have no idea what was going on there. Since then I was using `typed-process` in my code extensively and haven't observed the issue. I suppose it was the fault of our code.

So the recommendation is to prefer `typed-process` over `process` whenever possible.

**Comment by iamrecursion** [comment]
Then I think the best path forward regarding this is to gut the `shelly` dependency and rebuild based on `typed-process`!
