### ISSUE TITLE
Please provide an AppImage of luna-studio for download

### ISSUE THREAD

**Issue by probonopd** [luna/luna-studio#745]
Somehow apparently luna-studio uses [AppImage](https://appimage.org/) internally:

```
me@host:~$ strings /home/me/Downloads/lunaInstaller | grep AppImage
.AppImage
https://raw.githubusercontent.com/probonopd/AppImageKit/master/desktopintegration
Downloading AppImage desktopIntegration
https://github.com/probonopd/AppImages/raw/master/functions.sh
Downloading AppImage functions.sh
AppImage not created because of: 
AppImage
```

It would be cool if you could provide a readymade AppImage of luna-studio on GitHub Releases, so that one would not need to run `lunaInstaller` first.

AppImages are meant to be "one app = one file" with no installation needed.

**Comment by probonopd** [comment]
Indeed it turns out that the whole point of `lunaInstaller` seems to be downloading an AppImage and placing it into `./.luna/bin/luna-studio/1.0/luna-studio`. Can `luna-studio` be downloaded directly?

**Comment by wdanilo** [comment]
@probonopd We do it because we want to provide you with the possibility to install many versions of Luna Studio side by side. Currently the graphical installer allows you only to install Luna Studio, however, in near future it will also allow you to switch between currently installed versions.

Think about this situation - you are working on a real world, big project using Luna Studio version X. You see that there is an update to version Y. Using the described approach you can install the new, Y version and if anything stop working you can use `luna-manager switch luna-studio X` and it will re-bind symlinks so you can run older version without any problems with configurations or dependencies. It just makes the whole updating process reliable for real-world projects.

Does it make sense to you? Do you think providing alternative appImage in this situation could make any sense? Personally, I've got mixed feelings here.

**Comment by probonopd** [comment]
> If you are Linux user you could just download many AppImages and manage their versions manually.

Exactly. AppImage is especially designed to allow for the user to download multiple different versions. On macOS, the user can similarly have many different versions of the `.app` side by side.

**Comment by sylwiabr** [comment]
We decided to upload/store packages in releases section in luna-studio repository. To download please visit https://github.com/luna/luna-studio/releases/
