### ISSUE TITLE
manager-based build seems to be broken on OS X

### ISSUE THREAD

**Issue by binary132** [luna/luna-studio#813]
This is built against my upstream which has the S3 links corrected to use packages.luna-lang.org: https://github.com/luna/luna-studio/pull/812

```sh
luna-manager develop luna-studio --path "${HOME}/meta/dev/workshop/workspace" > results.txt 2> errors.txt
```

> results.txt (had already built and run with same errors, so git clone / etc weren't needed.)

http://pastebin.centos.org/543396/

> errors.txt

http://pastebin.centos.org/543381/

**Comment by wdanilo** [comment]
This error is very strange. I have never seen it before. It's clearly Haskell's stack error. 

Ok, after some minor investigation (https://stackoverflow.com/questions/48080510/stack-setup-error-solver-must-be-one-of-modular) my first bet is that you've got Cabal 2.0 isntalled system wide. Stack doesnt support Cabal 2.0 yet. However, if that's it, this is our bug that we allow to use systemwide Cabal installation instead of sandboxed one. What does `cabal --version` prints in your terminial?

**Comment by wdanilo** [comment]
Btw, wrong repo. Moving to luna-manager.

**Comment by wdanilo** [comment]
Issue moved to [luna/luna-manager #155](https://github.com/luna/luna-manager/issues/155) via [**ZenHub**](https://www.zenhub.com/)
