### ISSUE TITLE
Logs are not written to file on windows

### ISSUE THREAD

**Issue by ljkania** [luna/luna-studio#843]
Luna studio creates required log files but they are never filled with data.

**Comment by sylwiabr** [comment]
It looks like this commit cause the issue: https://github.com/luna/luna-studio/commit/a484b95abc6862e03bd033a94daf8eb081da8563 @mikusp can you take a look?

**Comment by sylwiabr** [comment]
It appears that logs are written to the file but after services are closed. This is why we can not get logs during studio running.

**Comment by mwu-tow** [comment]
From what I have observed the logs are written. As for the updating I'm not sure. First I observed that the file was completely written only after Studio closed. But in other situations I saw live updates. I have not given this much thought or observation. Not sure what is the rule for flushing the output but anyway this issue is not reproducible to me.
