### ISSUE TITLE
Dataframes visualizations with Plotly

### ISSUE THREAD

**Issue by lgawlik** [luna/luna-studio#980]
1. Single plot using Ploty from a dataframe. Dataframe structure: 6 columns:
 - position.x
- position.y
- position.z
- color.r
- color.g
- color.b
- color.a
- size

2. for now we are hardcoding layout like plot type, background color, axis, legend in JS script inside visualization
3. if there is a missing column from (position.x,position.y,position.z) I will assume that position in this direction is 0
4. default color will be orange

**Comment by wdanilo** [comment]
I'd change the column names to reflect whats inside. Basically when new dataframes arrive we will switch from 3 columns of `x`, `y` and `z` to a single containing a vector of 3 numbers in order to have better memory locality and preformance. Then such field would be just named `position`, thus I would already start naming fields in similar fashion. Lets use `position.x`, `position.y`, `position.z`, `color.r`, `color.g`, `color.b`.

**Comment by wdanilo** [comment]
Moreover, can we add some more data, like point size (attrib name `scale`) or line width (name `lineWidth`) ? They would be very useful for visualization of more complex relations.

**Comment by sylwiabr** [comment]
I think `scale` should be a range for each axis not a point size

**Comment by sylwiabr** [comment]
`label` will be added as an extra column

**Comment by piotrMocz** [comment]
How do I test it? @sylwiabr

**Comment by piotrMocz** [comment]
This task is no longer valid due to a change in requirements.

**Comment by piotrMocz** [comment]
Please disregard the previous message: it's still on 😂 @sylwiabr will continue working on this task, as time will allow.

**Comment by sylwiabr** [comment]
Issue moved to [luna/dataframes #150](https://github.com/luna/dataframes/issues/150) via [**ZenHub**](https://www.zenhub.com/)
